{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Module 4\n",
    "\n",
    "# In this module we’ll be looking at data from the New York City tree census:\n",
    "    \n",
    "# https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh\n",
    "\n",
    "# This data is collected by volunteers across the city, and is meant to catalog information\n",
    "# about every single tree in the city.\n",
    "\n",
    "# Build a dash app for a arborist studying the health of various tree species (as defined by the\n",
    "# variable ‘spc_common’) across each borough (defined by the variable ‘borough’). This\n",
    "# arborist would like to answer the following two questions for each species and in each\n",
    "# borough:\n",
    "    \n",
    "# 1. What proportion of trees are in good, fair, or poor health according to the ‘health’\n",
    "#   variable?\n",
    "# 2. Are stewards (steward activity measured by the ‘steward’ variable) having an impact\n",
    "#   on the health of trees?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Getting data from NYC tree census, limiting it only columns needed for Q1, \n",
    "# filtering out NaN and nan values, and then reading it into a pandas data frame.\n",
    "# I wrote string without spaces, bt included \".replace(' ', '%20')\" to be safe\n",
    "api_url1 = ('https://data.cityofnewyork.us/resource/nwxe-4ae8.json?$limit=700000&' +\\\n",
    "    '$offset=0&$select=count(tree_id),boroname,spc_common,health,steward&' +\\\n",
    "    '$where=health!=%27NaN%27%20and%20spc_common!=%27nan%27' +\\\n",
    "    '&$group=boroname,health,steward,spc_common').replace(' ', '%20')\n",
    "trees_all = pd.read_json(api_url1)\n",
    "# Getting data from NYC tree census, limiting it only columns needed for Q2, \n",
    "# filtering out NaN and nan values, and then reading it into a pandas data frame.\n",
    "api_url2 = ('https://data.cityofnewyork.us/resource/nwxe-4ae8.json?$limit=700000&' +\\\n",
    "    '$offset=0&$select=tree_id,boroname,spc_common,health,steward&' +\\\n",
    "    '$where=health!=%27NaN%27%20and%20spc_common!=%27nan%27').replace(' ', '%20')\n",
    "trees_2d = pd.read_json(api_url2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# To facilitate sorting for the 'steward' value in the \n",
    "# visualizations, this code changes the 'None' value to '0'\n",
    "def label_steward (row):\n",
    "   if row['steward'] == 'None' :\n",
    "      return '0'\n",
    "   return row['steward']\n",
    "\n",
    "trees_all['nbr_stewards'] = trees_all.apply (lambda row: label_steward(row), axis=1)\n",
    "trees_2d['nbr_stewards'] = trees_2d.apply (lambda row: label_steward(row), axis=1)\n",
    "trees_2d.columns = ['Borough','Health','Species','steward','tree_id','Nbr Stewards']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This code uses the trees_all dataframe to build a dataframe (trees_borough_health) for question 1 based on borough\n",
    "trees_borough1 = trees_all.groupby(['boroname','health']).agg({'count_tree_id': [np.sum]})\n",
    "trees_borough1.rename(index=str, columns={\"count_tree_id\": \"Tree Count\"})\n",
    "trees_borough1_df = pd.DataFrame(trees_borough1.to_records())\n",
    "trees_borough2 = trees_all.groupby(['boroname']).agg({'count_tree_id': [np.sum]})\n",
    "trees_borough2.rename(index=str, columns={\"count_tree_id\": \"Total Tree Count\"})\n",
    "trees_borough2_df = pd.DataFrame(trees_borough2.to_records())\n",
    "trees_borough_health = pd.merge(trees_borough1_df, trees_borough2_df, how='left', on='boroname')\n",
    "trees_borough_health.columns = ['Borough','Health','Tree Counts','Total Tree Counts']\n",
    "trees_borough_health['Proportion'] = trees_borough_health['Tree Counts'] / trees_borough_health['Total Tree Counts']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This code uses the trees_all dataframe to build a dataframe (trees_species_health) for question 1 based on species\n",
    "trees_species1 = trees_all.groupby(['spc_common','health']).agg({'count_tree_id': [np.sum]})\n",
    "trees_species1.rename(index=str, columns={\"count_tree_id\": \"Tree Count\"})\n",
    "trees_species1_df = pd.DataFrame(trees_species1.to_records())\n",
    "trees_species2 = trees_all.groupby(['spc_common']).agg({'count_tree_id': [np.sum]})\n",
    "trees_species2.rename(index=str, columns={\"count_tree_id\": \"Total Tree Count\"})\n",
    "trees_species2_df = pd.DataFrame(trees_species2.to_records())\n",
    "trees_species_health = pd.merge(trees_species1_df, trees_species2_df, how='left', on='spc_common')\n",
    "trees_species_health.columns = ['Species','Health','Tree Counts','Total Tree Counts']\n",
    "trees_species_health['Proportion'] = trees_species_health['Tree Counts'] / trees_species_health['Total Tree Counts']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: Do not use the development server in a production environment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:20] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:21] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:21] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:21] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:21] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:21] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:21] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "[2019-04-07 20:01:31,447] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:31] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:01:31,449] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:31] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:01:34,897] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 3\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:34] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:01:34,905] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 3\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [07/Apr/2019 20:01:34] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:01:47,718] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:47] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:01:47,728] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:47] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:01:50,379] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 3\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:50] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:01:50,381] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 3\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:50] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:01:54,273] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 4\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [07/Apr/2019 20:01:54] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:01:54,275] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 4\n",
      "127.0.0.1 - - [07/Apr/2019 20:01:54] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:02:39,141] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 3\n",
      "127.0.0.1 - - [07/Apr/2019 20:02:39] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:02:39,149] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 3\n",
      "127.0.0.1 - - [07/Apr/2019 20:02:39] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:02:40,128] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:02:40] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:02:40,136] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [07/Apr/2019 20:02:40] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:02:41,299] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 1\n",
      "127.0.0.1 - - [07/Apr/2019 20:02:41] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:02:41,309] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 1\n",
      "127.0.0.1 - - [07/Apr/2019 20:02:41] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:04:34,011] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 4\n",
      "127.0.0.1 - - [07/Apr/2019 20:04:34] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:04:34,019] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 4\n",
      "127.0.0.1 - - [07/Apr/2019 20:04:34] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:04:36,525] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [07/Apr/2019 20:04:36] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:04:36,533] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 5\n",
      "127.0.0.1 - - [07/Apr/2019 20:04:36] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:04:43,685] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:04:43] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:04:43,693] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:04:43] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:01,309] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 1\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:01] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:01,319] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [07/Apr/2019 20:05:01] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:29,994] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 4\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:30] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:29,997] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 4\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:30] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:35,403] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 3\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:35] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:35,426] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 3\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:35] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:40,056] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [07/Apr/2019 20:05:40] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:40,058] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:40] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:43,616] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 1\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:43] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:43,630] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 1\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:43] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:50,238] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 0\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:50] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:50,252] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [07/Apr/2019 20:05:50] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:51,728] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 120, in update_spec_steward_output\n",
      "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 1\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:51] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:05:51,736] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 83, in update_spec_output\n",
      "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 392 vs 1\n",
      "127.0.0.1 - - [07/Apr/2019 20:05:51] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:06:06,740] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:06:06] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:06:06,748] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 2\n",
      "127.0.0.1 - - [07/Apr/2019 20:06:06] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:06:07,468] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 102, in update_boro_steward_output\n",
      "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 652167 vs 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [07/Apr/2019 20:06:07] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "[2019-04-07 20:06:07,479] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 35, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1073, in dispatch\n",
      "    response.set_data(self.callback_map[output]['callback'](*args))\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 969, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"<ipython-input-12-ab20dafcee34>\", line 61, in update_boro_output\n",
      "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1283, in wrapper\n",
      "    res = na_op(values, other)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1143, in na_op\n",
      "    result = _comp_method_OBJECT_ARRAY(op, x, y)\n",
      "  File \"C:\\Users\\Lelan\\Anaconda3\\lib\\site-packages\\pandas\\core\\ops.py\", line 1120, in _comp_method_OBJECT_ARRAY\n",
      "    result = libops.vec_compare(x, y, op)\n",
      "  File \"pandas\\_libs\\ops.pyx\", line 128, in pandas._libs.ops.vec_compare\n",
      "ValueError: Arrays were different lengths: 15 vs 1\n",
      "127.0.0.1 - - [07/Apr/2019 20:06:07] \"POST /_dash-update-component HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "\n",
    "external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']\n",
    "\n",
    "# setting up datasets for use in callbacks\n",
    "df_boro = trees_borough_health\n",
    "df_spec = trees_species_health\n",
    "\n",
    "# setting up drop-downs \n",
    "borough_drop_down = df_boro['Borough'].unique()\n",
    "species_drop_down = df_spec['Species'].unique()\n",
    "\n",
    "app = dash.Dash(__name__, external_stylesheets=external_stylesheets)\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H1('Proportions of Health Status by Borough'),\n",
    "    html.Div('''\n",
    "        Borough\n",
    "    '''),\n",
    "    dcc.Dropdown(\n",
    "        id='borough-dropdown',\n",
    "        options=[{'label': i, 'value': i} for i in borough_drop_down],\n",
    "        multi=True, \n",
    "        value='Bronx'\n",
    "    ),\n",
    "    dcc.Graph(\n",
    "        id='borough-graph'    \n",
    "    ),\n",
    "    html.H1('Proportions of Health Status by Species'),\n",
    "    html.Div('''\n",
    "        Species\n",
    "    '''),\n",
    "    dcc.Dropdown(\n",
    "        id='species-dropdown',\n",
    "        options=[{'label': i, 'value': i} for i in species_drop_down], \n",
    "        multi=True, \n",
    "        value='American beech'\n",
    "    ),\n",
    "    dcc.Graph(\n",
    "        id='species-graph'    \n",
    "    ), \n",
    "    html.H1('Borough Tree Health vs Stewards 2d Histogram'),\n",
    "    dcc.Graph(\n",
    "        id='borough-steward-graph'\n",
    "    ), \n",
    "    html.H1('Species Tree Health vs Stewards 2d Histogram'),\n",
    "    dcc.Graph(\n",
    "        id='species-steward-graph'\n",
    "    )\n",
    "    ])\n",
    "\n",
    "# health status by borough\n",
    "@app.callback(\n",
    "    dash.dependencies.Output('borough-graph', 'figure'),\n",
    "    [dash.dependencies.Input('borough-dropdown', 'value')])\n",
    "\n",
    "def update_boro_output(borough_dropdown_value):\n",
    "    html.H1('Proportions of Health Status by Borough'),\n",
    "    html.Div('''\n",
    "        Borough\n",
    "    '''),\n",
    "    dff = df_boro[df_boro['Borough'] == borough_dropdown_value]\n",
    "    figure = {\n",
    "            'data': [\n",
    "                {'x': dff.Borough[dff['Health'] == 'Good'], 'y': dff.Proportion[dff['Health'] == 'Good'], 'type': 'bar', 'name': 'Good'},\n",
    "                {'x': dff.Borough[dff['Health'] == 'Fair'], 'y': dff.Proportion[dff['Health'] == 'Fair'], 'type': 'bar', 'name': 'Fair'},\n",
    "                {'x': dff.Borough[dff['Health'] == 'Poor'], 'y': dff.Proportion[dff['Health'] == 'Poor'], 'type': 'bar', 'name': 'Poor'}\n",
    "            ],\n",
    "            'layout': {\n",
    "                'title': 'Proportions of Health Status by Borough'\n",
    "                    }\n",
    "            }\n",
    "    return figure \n",
    "\n",
    "# health status by species\n",
    "@app.callback(\n",
    "    dash.dependencies.Output('species-graph', 'figure'),\n",
    "    [dash.dependencies.Input('species-dropdown', 'value')])\n",
    "\n",
    "def update_spec_output(species_dropdown_value):\n",
    "    html.H1('Proportions of Health Status by Species'),\n",
    "    html.Div('''\n",
    "        Species\n",
    "    '''),\n",
    "    dff = df_spec[df_spec['Species'] == species_dropdown_value]\n",
    "    figure = {\n",
    "            'data': [\n",
    "                {'x': dff.Species[dff['Health'] == 'Good'], 'y': dff.Proportion[dff['Health'] == 'Good'], 'type': 'bar', 'name': 'Good'},\n",
    "                {'x': dff.Species[dff['Health'] == 'Fair'], 'y': dff.Proportion[dff['Health'] == 'Fair'], 'type': 'bar', 'name': 'Fair'},\n",
    "                {'x': dff.Species[dff['Health'] == 'Poor'], 'y': dff.Proportion[dff['Health'] == 'Poor'], 'type': 'bar', 'name': 'Poor'}\n",
    "            ],\n",
    "            'layout': {\n",
    "                'title': 'Proportions of Health Status by Species'\n",
    "                    }\n",
    "            }\n",
    "    return figure \n",
    "\n",
    "# 2d histogram of steward count vs health count filtered by selected borough\n",
    "@app.callback(\n",
    "    dash.dependencies.Output('borough-steward-graph', 'figure'),\n",
    "    [dash.dependencies.Input('borough-dropdown', 'value')])\n",
    "\n",
    "def update_boro_steward_output(borough_dropdown_value):\n",
    "    html.H1('Borough Tree Health vs Stewards 2d Histogram'),\n",
    "    dff = trees_2d[trees_2d['Borough'] == borough_dropdown_value]\n",
    "    figure = {\n",
    "            'data': [\n",
    "                {'x': dff['Health'], 'y': dff['Nbr Stewards'], 'type': 'histogram2d'}\n",
    "            ],\n",
    "            'layout': {\n",
    "                'title': 'Borough Tree Health vs Stewards 2d Histogram'\n",
    "                    }\n",
    "            }\n",
    "    \n",
    "    return figure \n",
    "\n",
    "# 2d histogram of steward count vs health count filtered by selected species\n",
    "@app.callback(\n",
    "    dash.dependencies.Output('species-steward-graph', 'figure'),\n",
    "    [dash.dependencies.Input('species-dropdown', 'value')])\n",
    "\n",
    "def update_spec_steward_output(species_dropdown_value):\n",
    "    html.H1('Species Tree Health vs Stewards 2d Histogram'),\n",
    "    dff = trees_2d[trees_2d['Species'] == species_dropdown_value]\n",
    "    figure = {\n",
    "            'data': [\n",
    "                {'x': dff['Health'], 'y': dff['Nbr Stewards'], 'type': 'histogram2d'}\n",
    "            ],\n",
    "            'layout': {\n",
    "                'title': 'Species Tree Health vs Stewards 2d Histogram'\n",
    "                    }\n",
    "            }\n",
    "    return figure \n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
